In [1]:
import pandas as pd
import requests
import re
import string

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ba6b4fb1957e70c09a674f8a495f825b&page=1')

In [3]:
df1 = pd.DataFrame(response.json()['results'])

In [4]:
df1[['title','overview','genre_ids']]

,title,overview,genre_ids
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]"
4,12 Angry Men,The defense and the prosecution have rested an...,[18]
5,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...","[16, 10751, 14]"
6,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","[35, 18, 10749]"
7,The Dark Knight,Batman raises the stakes in his war on crime. ...,"[18, 28, 80, 53]"
8,Parasite,"All unemployed, Ki-taek's family takes peculia...","[35, 53, 18]"
9,The Green Mile,A supernatural tale set on death row in a Sout...,"[14, 18, 80]"
10,Your Name.,High schoolers Mitsuha and Taki are complete s...,"[16, 10749, 18]"
11,Pulp Fiction,"A burger-loving hit man, his philosophical par...","[53, 80]"
12,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,"[12, 14, 28]"
13,Forrest Gump,A man with a low IQ has accomplished great thi...,"[35, 18, 10749]"
14,The Count of Monte-Cristo,Edmond Dantes becomes the target of a sinister...,"[12, 36, 28, 18, 10749, 53]"
15,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...","[18, 80]"
16,Impossible Things,"After the death of her abusive husband, Matild...","[10751, 18]"
17,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,[37]
18,Seven Samurai,A samurai answers a village's request for prot...,"[28, 18]"
19,Grave of the Fireflies,"In the final months of World War II, 14-year-o...","[16, 18, 10752]"

In [5]:
df = pd.DataFrame()

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [7]:
for i in range(1,479):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ba6b4fb1957e70c09a674f8a495f825b&page={}'.format(i))
  temp_df = pd.DataFrame(response.json()['results'])
  df = pd.concat([df, temp_df], ignore_index=True)

df = df[['title','overview','genre_ids']]

In [8]:
df.shape

(9560, 3)

In [9]:
df.head()

,title,overview,genre_ids
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]"
4,12 Angry Men,The defense and the prosecution have rested an...,[18]

In [10]:
df['overview'][220]

"With Ran, legendary director Akira Kurosawa reimagines Shakespeare's King Lear as a singular historical epic set in sixteenth-century Japan. Majestic in scope, the film is Kurosawa's late-life masterpiece, a profound examination of the folly of war and the crumbling of one family under the weight of betrayal, greed, and the insatiable thirst for power."

In [11]:
df_overview = df['overview']

In [12]:
df_overview

0       Imprisoned in the 1940s for the double murder ...
1       Spanning the years 1945 to 1955, a chronicle o...
2       In the continuing saga of the Corleone crime f...
3       The true story of how businessman Oskar Schind...
4       The defense and the prosecution have rested an...
                              ...
9555    The heroic Leonidas, armed with nothing but le...
9556    Johnny is a successful banker with great respe...
9557    Disturbing and mysterious things begin to happ...
9558    Old and forgotten, comedian Aldo is brought by...
9559    When young Joshua learns that he will be going...
Name: overview, Length: 9560, dtype: object

#Lower casing

In [13]:
df_overview = df_overview.str.lower()

In [14]:
df_overview[220]

"with ran, legendary director akira kurosawa reimagines shakespeare's king lear as a singular historical epic set in sixteenth-century japan. majestic in scope, the film is kurosawa's late-life masterpiece, a profound examination of the folly of war and the crumbling of one family under the weight of betrayal, greed, and the insatiable thirst for power."

#Remove HTML tags

In [15]:
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r' ', text)

In [16]:
df_overview = df_overview.apply(remove_html_tags)

In [17]:
df_overview[220]

"with ran, legendary director akira kurosawa reimagines shakespeare's king lear as a singular historical epic set in sixteenth-century japan. majestic in scope, the film is kurosawa's late-life masterpiece, a profound examination of the folly of war and the crumbling of one family under the weight of betrayal, greed, and the insatiable thirst for power."

#Remove URL's

In [18]:
def remove_urls(text):
  pattern = re.compile(r'https?:\\/s+|www\.\s+')
  return pattern.sub(r' ', text)

In [19]:
df_overview = df_overview.apply(remove_urls)

In [20]:
df_overview[220]

"with ran, legendary director akira kurosawa reimagines shakespeare's king lear as a singular historical epic set in sixteenth-century japan. majestic in scope, the film is kurosawa's late-life masterpiece, a profound examination of the folly of war and the crumbling of one family under the weight of betrayal, greed, and the insatiable thirst for power."

#Remove Punctuation

In [21]:

exclude = string.punctuation

In [22]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
def remove_punctuation(text):
  for char in exclude:
    text = text.replace(char, ' ')

  return text

In [24]:
df_overview = df_overview.apply(remove_punctuation)

In [25]:
df_overview[220]

'with ran  legendary director akira kurosawa reimagines shakespeare s king lear as a singular historical epic set in sixteenth century japan  majestic in scope  the film is kurosawa s late life masterpiece  a profound examination of the folly of war and the crumbling of one family under the weight of betrayal  greed  and the insatiable thirst for power '

#Chat Word Treatement

In [26]:
#Need Dictionary for short wordsor abbreviations for original words
new_text = []
def chat_words(text):
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append((chat_words[w.upper()]))
    else:
      new_text.append(w)

  return ' '.join(new_text)

#Spelling Correction

In [27]:
from textblob import TextBlob

In [28]:
list_text = []
for i in range(1,28680):
  textblob = TextBlob(str(i))
  temp_text = textblob.correct().string
  list_text.append(temp_text)

In [29]:
list_text

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138',
 '139',
 '140',
 '141',
 '142',
 '143',
 '144',
 '145',
 '146',
 '147',
 '148',
 '149',
 '150',
 '151',
 '152',
 '153',
 '154',
 '155',
 '156',
 '157',
 '158',
 '159',
 '160',
 '161',
 '162',
 '163',
 '164',
 '165',
 '166',
 '167',
 '168',
 '169',
 '170',
 '171',
 '172',
 '173',
 '174',
 '175',
 '176',
 '177',
 '178',
 '179',
 '180',
 '181',
 '182',
 '183',
 '184',
 '185',
 '186',
 '187',
 '188',
 '189',
 '190',
 '191',
 '192',
 '193',
 '194',
 '195',
 '196',
 '197',
 '198',
 '199',
 '200',
 '201',
 '202',
 '203',
 '204',
 '205',
 '206',
 '207',
 '208',
 '209',
 '210',
 '211',
 '212',
 '213',
 '214',
 '215',
 '216',
 '217',
 '218',
 '219',
 '220',
 '221',
 '222',
 '223',
 '224',
 '225',
 '226',
 '227',
 '228',
 '229',
 '230',
 '231',
 '232',
 '233',
 '234',
 '235',
 '236',
 '237',
 '238',
 '239',
 '240',
 '241',
 '242',
 '243',
 '244',
 '245',
 '246',
 '247',
 '248',
 '249',
 '250',
 '251',
 '252',
 '253',
 '254',
 '255',
 '256',
 '257',
 '258',
 '259',
 '260',
 '261',
 '262',
 '263',
 '264',
 '265',
 '266',
 '267',
 '268',
 '269',
 '270',
 '271',
 '272',
 '273',
 '274',
 '275',
 '276',
 '277',
 '278',
 '279',
 '280',
 '281',
 '282',
 '283',
 '284',
 '285',
 '286',
 '287',
 '288',
 '289',
 '290',
 '291',
 '292',
 '293',
 '294',
 '295',
 '296',
 '297',
 '298',
 '299',
 '300',
 '301',
 '302',
 '303',
 '304',
 '305',
 '306',
 '307',
 '308',
 '309',
 '310',
 '311',
 '312',
 '313',
 '314',
 '315',
 '316',
 '317',
 '318',
 '319',
 '320',
 '321',
 '322',
 '323',
 '324',
 '325',
 '326',
 '327',
 '328',
 '329',
 '330',
 '331',
 '332',
 '333',
 '334',
 '335',
 '336',
 '337',
 '338',
 '339',
 '340',
 '341',
 '342',
 '343',
 '344',
 '345',
 '346',
 '347',
 '348',
 '349',
 '350',
 '351',
 '352',
 '353',
 '354',
 '355',
 '356',
 '357',
 '358',
 '359',
 '360',
 '361',
 '362',
 '363',
 '364',
 '365',
 '366',
 '367',
 '368',
 '369',
 '370',
 '371',
 '372',
 '373',
 '374',
 '375',
 '376',
 '377',
 '378',
 '379',
 '380',
 '381',
 '382',
 '383',
 '384',
 '385',
 '386',
 '387',
 '388',
 '389',
 '390',
 '391',
 '392',
 '393',
 '394',
 '395',
 '396',
 '397',
 '398',
 '399',
 '400',
 '401',
 '402',
 '403',
 '404',
 '405',
 '406',
 '407',
 '408',
 '409',
 '410',
 '411',
 '412',
 '413',
 '414',
 '415',
 '416',
 '417',
 '418',
 '419',
 '420',
 '421',
 '422',
 '423',
 '424',
 '425',
 '426',
 '427',
 '428',
 '429',
 '430',
 '431',
 '432',
 '433',
 '434',
 '435',
 '436',
 '437',
 '438',
 '439',
 '440',
 '441',
 '442',
 '443',
 '444',
 '445',
 '446',
 '447',
 '448',
 '449',
 '450',
 '451',
 '452',
 '453',
 '454',
 '455',
 '456',
 '457',
 '458',
 '459',
 '460',
 '461',
 '462',
 '463',
 '464',
 '465',
 '466',
 '467',
 '468',
 '469',
 '470',
 '471',
 '472',
 '473',
 '474',
 '475',
 '476',
 '477',
 '478',
 '479',
 '480',
 '481',
 '482',
 '483',
 '484',
 '485',
 '486',
 '487',
 '488',
 '489',
 '490',
 '491',
 '492',
 '493',
 '494',
 '495',
 '496',
 '497',
 '498',
 '499',
 '500',
 '501',
 '502',
 '503',
 '504',
 '505',
 '506',
 '507',
 '508',
 '509',
 '510',
 '511',
 '512',
 '513',
 '514',
 '515',
 '516',
 '517',
 '518',
 '519',
 '520',
 '521',
 '522',
 '523',
 '524',
 '525',
 '526',
 '527',
 '528',
 '529',
 '530',
 '531',
 '532',
 '533',
 '534',
 '535',
 '536',
 '537',
 '538',
 '539',
 '540',
 '541',
 '542',
 '543',
 '544',
 '545',
 '546',
 '547',
 '548',
 '549',
 '550',
 '551',
 '552',
 '553',
 '554',
 '555',
 '556',
 '557',
 '558',
 '559',
 '560',
 '561',
 '562',
 '563',
 '564',
 '565',
 '566',
 '567',
 '568',
 '569',
 '570',
 '571',
 '572',
 '573',
 '574',
 '575',
 '576',
 '577',
 '578',
 '579',
 '580',
 '581',
 '582',
 '583',
 '584',
 '585',
 '586',
 '587',
 '588',
 '589',
 '590',
 '591',
 '592',
 '593',
 '594',
 '595',
 '596',
 '597',
 '598',
 '599',
 '600',
 '601',
 '602',
 '603',
 '604',
 '605',
 '606',
 '607',
 '608',
 '609',
 '610',
 '611',
 '612',
 '613',
 '614',
 '615',
 '616',
 '617',
 '618',
 '619',
 '620',
 '621',
 '622',
 '623',
 '624',
 '625',
 '626',
 '627',
 '628',
 '629',
 '630',
 '631',
 '632',
 '633',
 '634',
 '635',
 '636',
 '637',
 '638',
 '639',
 '640',
 '641',
 '642',
 '643',
 '644',
 '645',
 '646',
 '647',
 '648',
 '649',
 '650',
 '651',
 '652',
 '653',
 '654',
 '655',
 '656',
 '657',
 '658',
 '659',
 '660',
 '661',
 '662',
 '663',
 '664',
 '665',
 '666',
 '667',
 '668',
 '669',
 '670',
 '671',
 '672',
 '673',
 '674',
 '675',
 '676',
 '677',
 '678',
 '679',
 '680',
 '681',
 '682',
 '683',
 '684',
 '685',
 '686',
 '687',
 '688',
 '689',
 '690',
 '691',
 '692',
 '693',
 '694',
 '695',
 '696',
 '697',
 '698',
 '699',
 '700',
 '701',
 '702',
 '703',
 '704',
 '705',
 '706',
 '707',
 '708',
 '709',
 '710',
 '711',
 '712',
 '713',
 '714',
 '715',
 '716',
 '717',
 '718',
 '719',
 '720',
 '721',
 '722',
 '723',
 '724',
 '725',
 '726',
 '727',
 '728',
 '729',
 '730',
 '731',
 '732',
 '733',
 '734',
 '735',
 '736',
 '737',
 '738',
 '739',
 '740',
 '741',
 '742',
 '743',
 '744',
 '745',
 '746',
 '747',
 '748',
 '749',
 '750',
 '751',
 '752',
 '753',
 '754',
 '755',
 '756',
 '757',
 '758',
 '759',
 '760',
 '761',
 '762',
 '763',
 '764',
 '765',
 '766',
 '767',
 '768',
 '769',
 '770',
 '771',
 '772',
 '773',
 '774',
 '775',
 '776',
 '777',
 '778',
 '779',
 '780',
 '781',
 '782',
 '783',
 '784',
 '785',
 '786',
 '787',
 '788',
 '789',
 '790',
 '791',
 '792',
 '793',
 '794',
 '795',
 '796',
 '797',
 '798',
 '799',
 '800',
 '801',
 '802',
 '803',
 '804',
 '805',
 '806',
 '807',
 '808',
 '809',
 '810',
 '811',
 '812',
 '813',
 '814',
 '815',
 '816',
 '817',
 '818',
 '819',
 '820',
 '821',
 '822',
 '823',
 '824',
 '825',
 '826',
 '827',
 '828',
 '829',
 '830',
 '831',
 '832',
 '833',
 '834',
 '835',
 '836',
 '837',
 '838',
 '839',
 '840',
 '841',
 '842',
 '843',
 '844',
 '845',
 '846',
 '847',
 '848',
 '849',
 '850',
 '851',
 '852',
 '853',
 '854',
 '855',
 '856',
 '857',
 '858',
 '859',
 '860',
 '861',
 '862',
 '863',
 '864',
 '865',
 '866',
 '867',
 '868',
 '869',
 '870',
 '871',
 '872',
 '873',
 '874',
 '875',
 '876',
 '877',
 '878',
 '879',
 '880',
 '881',
 '882',
 '883',
 '884',
 '885',
 '886',
 '887',
 '888',
 '889',
 '890',
 '891',
 '892',
 '893',
 '894',
 '895',
 '896',
 '897',
 '898',
 '899',
 '900',
 '901',
 '902',
 '903',
 '904',
 '905',
 '906',
 '907',
 '908',
 '909',
 '910',
 '911',
 '912',
 '913',
 '914',
 '915',
 '916',
 '917',
 '918',
 '919',
 '920',
 '921',
 '922',
 '923',
 '924',
 '925',
 '926',
 '927',
 '928',
 '929',
 '930',
 '931',
 '932',
 '933',
 '934',
 '935',
 '936',
 '937',
 '938',
 '939',
 '940',
 '941',
 '942',
 '943',
 '944',
 '945',
 '946',
 '947',
 '948',
 '949',
 '950',
 '951',
 '952',
 '953',
 '954',
 '955',
 '956',
 '957',
 '958',
 '959',
 '960',
 '961',
 '962',
 '963',
 '964',
 '965',
 '966',
 '967',
 '968',
 '969',
 '970',
 '971',
 '972',
 '973',
 '974',
 '975',
 '976',
 '977',
 '978',
 '979',
 '980',
 '981',
 '982',
 '983',
 '984',
 '985',
 '986',
 '987',
 '988',
 '989',
 '990',
 '991',
 '992',
 '993',
 '994',
 '995',
 '996',
 '997',
 '998',
 '999',
 '1000',
 ...]

#Removing StopWords

In [30]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [31]:
new_list = []
def remove_stopwords(text):
  for word in text.split():
    if word in stopwords.words('english'):
      new_list.append(" ")
    else:
      new_list.append(word)

  return ' '.join(new_list)

In [32]:
df_overview.apply(remove_stopwords)

KeyboardInterrupt:

#Tokenization

In [36]:
from nltk import word_tokenize,sent_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [40]:
df_overview = df_overview.apply(word_tokenize)

In [41]:
df_overview[220]

['with',
 'ran',
 'legendary',
 'director',
 'akira',
 'kurosawa',
 'reimagines',
 'shakespeare',
 's',
 'king',
 'lear',
 'as',
 'a',
 'singular',
 'historical',
 'epic',
 'set',
 'in',
 'sixteenth',
 'century',
 'japan',
 'majestic',
 'in',
 'scope',
 'the',
 'film',
 'is',
 'kurosawa',
 's',
 'late',
 'life',
 'masterpiece',
 'a',
 'profound',
 'examination',
 'of',
 'the',
 'folly',
 'of',
 'war',
 'and',
 'the',
 'crumbling',
 'of',
 'one',
 'family',
 'under',
 'the',
 'weight',
 'of',
 'betrayal',
 'greed',
 'and',
 'the',
 'insatiable',
 'thirst',
 'for',
 'power']

In [42]:
#using spacy but Not run the code
import spacy
NLP = spacy.load('en_core_web_sm')

In [44]:
doc = NLP(str(df_overview))

In [49]:
tokens = []
for token in doc:
  print(token)
  tokens.append(token)

0

[
imprisoned
,
in
,
the
,
1940s
,
for
,
the
,
double
,
...


1

[
spanning
,
the
,
years
,
1945
,
to
,
1955
,
a
,
chro
...


2

[
in
,
the
,
continuing
,
saga
,
of
,
the
,
corleone
,
...


3

[
the
,
true
,
story
,
of
,
how
,
businessman
,
oskar
...


4

[
the
,
defense
,
and
,
the
,
prosecution
,
have
,
re
...


...


9555

[
the
,
heroic
,
leonidas
,
armed
,
with
,
nothing
,
...


9556

[
johnny
,
is
,
a
,
successful
,
banker
,
with
,
grea
...


9557

[
disturbing
,
and
,
mysterious
,
things
,
begin
,
t
...


9558

[
old
,
and
,
forgotten
,
comedian
,
aldo
,
is
,
brou
...


9559

[
when
,
young
,
joshua
,
learns
,
that
,
he
,
will
,
...


Name
:
overview
,
Length
:
9560
,
dtype
:
object

#Stemming

In [46]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
ps = PorterStemmer()
wl = WordNetLemmatizer()

In [67]:
def stemming(text):
  for word in text.split():
   ps.stem(word)

#Lemmatization

In [ ]:
#in progress